Repository cse112-group10/cse112-sp22-group10, pull requests merged in 2022-05, with the labels that each got.

#7 added users table migration file
  source/backend/database/migrations/20220502190819_users.js
Labels: enhancement

#8 added migrations for two tables
  source/backend/database/migrations/20220502220754_saved_recipes.js
  source/backend/database/migrations/20220502221909_completed_recipes.js
Labels: database

#11 Backend boilerplate
  .gitignore
  source/backend/app.js
  source/backend/bin/www
  source/backend/package-lock.json
  source/backend/package.json
  source/backend/routes/auth.js
  source/backend/routes/recipes.js
  source/backend/routes/users.js
Labels: new feature

#29 added token auth functions + middleware verifyToken function + GET /u…
  source/backend/.env_sample
  source/backend/app.js
  source/backend/auth/tokenUtil.js
  source/backend/database/dbConfig.js
  source/backend/database/models/usersModel.js
  source/backend/middleware/verifyUserToken.js
  source/backend/package-lock.json
  source/backend/package.json
  source/backend/routes/users.js
Labels: new feature, rest api, user route

#13 added docker file and compose for CI/CD
  docker-compose.yml
  source/Dockerfile
  source/backend/Dockerfile
Labels: new feature
